"""add language to posts

Revision ID: 496bf55e25e8
Revises: 229e6f7906d4
Create Date: 2026-01-19 10:10:14.247543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496bf55e25e8'
down_revision = '229e6f7906d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
